### ISSUE TITLE
Can paragraph's text come before \v?

### ISSUE THREAD

**Issue by kavitharaju** [usfm-bible/tcdocs#4]
Trying to model the USFM specification with formal grammars, one major issue I notice there, related to clearly defining hierarchy is, _the two overlapping structures of paragraphs and book-chapter-verse_. For instance, as per the paragraph-based structure, \v markers are just character level markups. So, within a chapter is it valid for text to occur before the first \v marker? As per the spec, I don't see any such restrictions being enforced(Or is there?). As per my understanding, it is correct for paragraphs to have texts not bound by \v marker when inside a sidebar(\esb), peripherals etc, but just not within a chapter. It would be good to have the specification clearly define the rules here.

**Comment by KentSpiel** [comment]
I think that there may be some edge cases. For example:
`\c 2` 
`\p (`
`\v1 parenthetical text)`
I am using chapter 2 here since chapter 1 is a special case and needs to be  dealt with separately (In Peripheral books  \c 1 is optional)
The question also relates to headings that  appear before \v 1.  Are they part of verse 1 or verse 0?

**Comment by mhosken** [comment]
Yes, you can have text before a \v in a paragraph after a \c
