### ISSUE TITLE
Well-formed versus Valid USFM

### ISSUE THREAD

**Issue by jonathanrobie** [usfm-bible/tcdocs#7]
Do we need a concept of well-formed USFM, analogous to well-formed XML?  This would be USFM that does not validate against the schema but can be parsed in order to correct errors.

**Comment by mhosken** [comment]
I am in favour of a definition of well formedness for any representation of the scripture content model. Thus one can have well formed XML and well formed USFM. This is a lesser requirement than a test for validity which requires conformance to a grammar and also conformance to semantic constraints.

The problem is that I don't see a way to get from an enhanced grammar to a definition of well formed USFM. I do hope we don't have to keep two grammars going in parallel. Perhaps the stylesheet can be designed to be sufficient to specify well formed USFM. I don't see the stylesheet as being sufficient to specify validity, though. And this raises the issue of extensibility for both the grammar and the well formedness and even the semantic constraints.

**Comment by mhosken** [comment]
Done
